<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" total="27" passed="21">
  <reporter-output>
  </reporter-output>
  <suite name="P2P-FileSharingCS490" duration-ms="215" started-at="2016-04-10T14:28:05Z" finished-at="2016-04-10T14:28:05Z">
    <groups>
    </groups>
    <test name="edu.ccsu.networking.udp.TimerTest" duration-ms="215" started-at="2016-04-10T14:28:05Z" finished-at="2016-04-10T14:28:05Z">
      <class name="edu.ccsu.networking.udp.TimerTest">
        <test-method status="FAIL" signature="testStopTimer()[pri:0, instance:testStopTimer(edu.ccsu.networking.udp.TimerTest)]" name="testStopTimer" duration-ms="106" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<100> but was:<102>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<100> but was:<102>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at edu.ccsu.networking.udp.TimerTest.testStopTimer(TimerTest.java:313)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:81)
	at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:69)
	at org.testng.TestRunner$1.run(TestRunner.java:682)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1005)
	at org.testng.TestRunner.privateRunJUnit(TestRunner.java:713)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStopTimer -->
        <test-method status="PASS" signature="testSetTimeOutInterval()[pri:0, instance:testSetTimeOutInterval(edu.ccsu.networking.udp.TimerTest)]" name="testSetTimeOutInterval" duration-ms="1" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetTimeOutInterval -->
        <test-method status="PASS" signature="testLongToInt2()[pri:0, instance:testLongToInt2(edu.ccsu.networking.udp.TimerTest)]" name="testLongToInt2" duration-ms="1" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLongToInt2 -->
        <test-method status="PASS" signature="testTimerTimeOut()[pri:0, instance:testTimerTimeOut(edu.ccsu.networking.udp.TimerTest)]" name="testTimerTimeOut" duration-ms="0" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTimerTimeOut -->
        <test-method status="FAIL" signature="testGetStartTime()[pri:0, instance:testGetStartTime(edu.ccsu.networking.udp.TimerTest)]" name="testGetStartTime" duration-ms="0" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The test case is a prototype.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The test case is a prototype.
	at org.junit.Assert.fail(Assert.java:88)
	at edu.ccsu.networking.udp.TimerTest.testGetStartTime(TimerTest.java:344)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:81)
	at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:69)
	at org.testng.TestRunner$1.run(TestRunner.java:682)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1005)
	at org.testng.TestRunner.privateRunJUnit(TestRunner.java:713)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetStartTime -->
        <test-method status="FAIL" signature="testGetEstimatedRTT()[pri:0, instance:testGetEstimatedRTT(edu.ccsu.networking.udp.TimerTest)]" name="testGetEstimatedRTT" duration-ms="0" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<2000> but was:<900>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<2000> but was:<900>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at edu.ccsu.networking.udp.TimerTest.testGetEstimatedRTT(TimerTest.java:220)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:81)
	at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:69)
	at org.testng.TestRunner$1.run(TestRunner.java:682)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1005)
	at org.testng.TestRunner.privateRunJUnit(TestRunner.java:713)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetEstimatedRTT -->
        <test-method status="PASS" signature="testSetSampleRTT()[pri:0, instance:testSetSampleRTT(edu.ccsu.networking.udp.TimerTest)]" name="testSetSampleRTT" duration-ms="1" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetSampleRTT -->
        <test-method status="FAIL" signature="testUpdateEstimatedRTT()[pri:0, instance:testUpdateEstimatedRTT(edu.ccsu.networking.udp.TimerTest)]" name="testUpdateEstimatedRTT" duration-ms="0" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<2000> but was:<900>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<2000> but was:<900>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at edu.ccsu.networking.udp.TimerTest.testUpdateEstimatedRTT(TimerTest.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:81)
	at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:69)
	at org.testng.TestRunner$1.run(TestRunner.java:682)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1005)
	at org.testng.TestRunner.privateRunJUnit(TestRunner.java:713)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateEstimatedRTT -->
        <test-method status="PASS" signature="testGetEstimatedRTT2()[pri:0, instance:testGetEstimatedRTT2(edu.ccsu.networking.udp.TimerTest)]" name="testGetEstimatedRTT2" duration-ms="1" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetEstimatedRTT2 -->
        <test-method status="PASS" signature="testSetTimeOutInterval2()[pri:0, instance:testSetTimeOutInterval2(edu.ccsu.networking.udp.TimerTest)]" name="testSetTimeOutInterval2" duration-ms="1" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetTimeOutInterval2 -->
        <test-method status="PASS" signature="testUpdateDevRTT()[pri:0, instance:testUpdateDevRTT(edu.ccsu.networking.udp.TimerTest)]" name="testUpdateDevRTT" duration-ms="0" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateDevRTT -->
        <test-method status="PASS" signature="testUpdateEstimatedRTT2()[pri:0, instance:testUpdateEstimatedRTT2(edu.ccsu.networking.udp.TimerTest)]" name="testUpdateEstimatedRTT2" duration-ms="0" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateEstimatedRTT2 -->
        <test-method status="PASS" signature="testSetEstimatedRTT()[pri:0, instance:testSetEstimatedRTT(edu.ccsu.networking.udp.TimerTest)]" name="testSetEstimatedRTT" duration-ms="1" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetEstimatedRTT -->
        <test-method status="FAIL" signature="testUpdateTimeOutInterval()[pri:0, instance:testUpdateTimeOutInterval(edu.ccsu.networking.udp.TimerTest)]" name="testUpdateTimeOutInterval" duration-ms="0" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<2000> but was:<900>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<2000> but was:<900>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at edu.ccsu.networking.udp.TimerTest.testUpdateTimeOutInterval(TimerTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:81)
	at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:69)
	at org.testng.TestRunner$1.run(TestRunner.java:682)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1005)
	at org.testng.TestRunner.privateRunJUnit(TestRunner.java:713)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateTimeOutInterval -->
        <test-method status="PASS" signature="testUpdateTimeOutInterval2()[pri:0, instance:testUpdateTimeOutInterval2(edu.ccsu.networking.udp.TimerTest)]" name="testUpdateTimeOutInterval2" duration-ms="0" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateTimeOutInterval2 -->
        <test-method status="PASS" signature="testLongToInt()[pri:0, instance:testLongToInt(edu.ccsu.networking.udp.TimerTest)]" name="testLongToInt" duration-ms="1" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLongToInt -->
        <test-method status="PASS" signature="testGetDevRTT()[pri:0, instance:testGetDevRTT(edu.ccsu.networking.udp.TimerTest)]" name="testGetDevRTT" duration-ms="0" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetDevRTT -->
        <test-method status="PASS" signature="testSetDevRTT()[pri:0, instance:testSetDevRTT(edu.ccsu.networking.udp.TimerTest)]" name="testSetDevRTT" duration-ms="0" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetDevRTT -->
        <test-method status="PASS" signature="testGetTimeOutInterval()[pri:0, instance:testGetTimeOutInterval(edu.ccsu.networking.udp.TimerTest)]" name="testGetTimeOutInterval" duration-ms="0" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetTimeOutInterval -->
        <test-method status="PASS" signature="testGetTimeOutInterval2()[pri:0, instance:testGetTimeOutInterval2(edu.ccsu.networking.udp.TimerTest)]" name="testGetTimeOutInterval2" duration-ms="0" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetTimeOutInterval2 -->
        <test-method status="PASS" signature="testGetSampleRTT2()[pri:0, instance:testGetSampleRTT2(edu.ccsu.networking.udp.TimerTest)]" name="testGetSampleRTT2" duration-ms="0" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetSampleRTT2 -->
        <test-method status="PASS" signature="testGetSampleRTT3()[pri:0, instance:testGetSampleRTT3(edu.ccsu.networking.udp.TimerTest)]" name="testGetSampleRTT3" duration-ms="0" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetSampleRTT3 -->
        <test-method status="PASS" signature="testGetDevRTT2()[pri:0, instance:testGetDevRTT2(edu.ccsu.networking.udp.TimerTest)]" name="testGetDevRTT2" duration-ms="0" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetDevRTT2 -->
        <test-method status="PASS" signature="testSetEstimatedRTT2()[pri:0, instance:testSetEstimatedRTT2(edu.ccsu.networking.udp.TimerTest)]" name="testSetEstimatedRTT2" duration-ms="1" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetEstimatedRTT2 -->
        <test-method status="PASS" signature="testStartTimer()[pri:0, instance:testStartTimer(edu.ccsu.networking.udp.TimerTest)]" name="testStartTimer" duration-ms="1" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStartTimer -->
        <test-method status="PASS" signature="testUpdateDevRTT2()[pri:0, instance:testUpdateDevRTT2(edu.ccsu.networking.udp.TimerTest)]" name="testUpdateDevRTT2" duration-ms="0" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateDevRTT2 -->
        <test-method status="FAIL" signature="testGetSampleRTT()[pri:0, instance:testGetSampleRTT(edu.ccsu.networking.udp.TimerTest)]" name="testGetSampleRTT" duration-ms="0" started-at="2016-04-10T10:28:05Z" finished-at="2016-04-10T10:28:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<2000> but was:<900>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<2000> but was:<900>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at edu.ccsu.networking.udp.TimerTest.testGetSampleRTT(TimerTest.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:81)
	at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:69)
	at org.testng.TestRunner$1.run(TestRunner.java:682)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1005)
	at org.testng.TestRunner.privateRunJUnit(TestRunner.java:713)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetSampleRTT -->
      </class> <!-- edu.ccsu.networking.udp.TimerTest -->
    </test> <!-- edu.ccsu.networking.udp.TimerTest -->
  </suite> <!-- P2P-FileSharingCS490 -->
</testng-results>
